<?php
$typeArr[1] = '公司概况';
$typeArr[2] = '生产中心';
$typeArr[3] = '益补类';
$typeArr[4] = '安神养颜类';
$typeArr[5] = '活血抗菌类';
$typeArr[6] = '止痛消炎类';
$typeArr[7] = '果粉类';
$typeArr[8] = '挥发优类';
$typeArr[9] = '产品展示';
$typeArr[10] = '动态新闻';
$typeArr[11] = '服务客户';
$typeArr[15] = '白芍提取物';
$typeArr[16] = '黄芪提取物';
$typeArr[17] = '葛根提取物';
$typeArr[18] = '淫羊藿提取物';
$typeArr[19] = '橘皮提取物';
$typeArr[20] = '番茄提取物';
$typeArr[21] = '枸杞提取物';
$typeArr[22] = '益母草提取物';
$typeArr[13] = '在线留言';
$typeArr[14] = '联系我们';
?>