{dede:type}
             <dt><h2>[<a href="[field:typelink /]"><b>[field:typename /]</b></a>]</h2></dt>
            {/dede:type}
			<!--{dede:channel type='son' noself='no'}
            <dd><a href='[field:typelink /]'>[field:typename/]</a></dd>
            {/dede:channel}-->
			
			{dede:channel type='son' row='10' noself='yes'} 
			<dd><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></dd>
			{/dede:channel}