<?php
$z[0]=Array("type","\r\n             <dt><h2>[<a href=\"[field:typelink /]\"><b>[field:typename /]</b></a>]</h2></dt>\r\n            ",0,130);
$z[1]=Array("channel","\r\n            <dd><a href='[field:typelink /]'>[field:typename/]</a></dd>\r\n            ",139,278);
$z[1][4]['type']="son";
$z[1][4]['noself']="no";
$z[2]=Array("channel"," \r\n			<dd><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></dd>\r\n			",291,447);
$z[2][4]['type']="son";
$z[2][4]['row']="10";
$z[2][4]['noself']="yes";

?>