<div class="list_box">
			<a href="[field:arcurl/]#content" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" /></a>
			<div class="ff">
				<div class="fl">
					<a href="[field:arcurl/]#content"				title="[field:title/]">[field:title/]</a>
				</div>
				<div class="fr"><a href="[field:arcurl/]#content"><span>查看详情</span></a></div>
			    <div class="clear"></div>
			</div>
		</div>