
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:bt itemname="标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bt>

<field:content itemname="内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:content>
