<?php
$z[0]=Array("global","",477,503);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n	<a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n		  ",555,794);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a>";
$z[2]=Array("global","",944,970);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",1050,1074);
$z[3][4]['name']="cfg_beian";

?>