<?php
$z[0]=Array("global","",1024,1050);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n	<a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n		  ",1102,1341);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a>";
$z[2]=Array("global","",2242,2268);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",2348,2372);
$z[3][4]['name']="cfg_beian";

?>