<?php
$z[0]=Array("globel","",333,360);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",968,994);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1034,1060);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1459,1485);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]#content\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	  ",1510,1771);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[4][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>