<?php
$z[0]=Array("field","",56,75);
$z[0][4]['name']="title";
$z[1]=Array("globel","",447,474);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1128,1154);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1194,1220);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1619,1645);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]#content\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	  ",1670,1931);
$z[5][4]['type']="top";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>