<?php
$z[0]=Array("field","",56,75);
$z[0][4]['name']="title";
$z[1]=Array("globel","",445,472);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",1120,1146);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1186,1212);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1611,1637);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]#content\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	  ",1662,1923);
$z[5][4]['type']="top";
$z[5][4]['row']="8";
$z[5][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>