<?php
$z[0]=Array("global","",83,109);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",126,153);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",176,206);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",263,289);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",315,344);
$z[4][4]['name']="cfg_adminemail";
$z[5]=Array("arclist"," \r\n<item> \r\n<link>http://127.0.0.1[field:arcurl/]</link>\r\n<title><![CDATA[[field:title function='html2text(@me)'/]]]></title> \r\n<author>[field:writer/]</author> \r\n<category>[field:typename/]</category> \r\n<pubDate>[field:pubdate function='strftime(\"%a, %d %b %Y %H:%M:%S +0800\",@me)'/]</pubDate> \r\n<guid>[field:arcurl/]</guid> \r\n<description><![CDATA[[field:description function='html2text(@me)'/]...]]></description> \r\n</item> \r\n",359,867);
$z[5][4]['row']="20";
$z[5][4]['col']="1";
$z[5][4]['titlelen']="100";
$z[5][4]['orderby']="pubdate";

?>