<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'SW50cm9kdWN0aW9u');
$cfg_Cs[2]=array(0,1,1,'UHJvZHVjdA==');
$cfg_Cs[3]=array(2,1,1,'5Liq5Lq65pCs5a625pyN5Yqh');
$cfg_Cs[4]=array(2,1,1,'5YWs5Y+45pCs5a625pyN5Yqh');
$cfg_Cs[5]=array(2,1,1,'6ZW/6YCU5pCs5a625pyN5Yqh');
$cfg_Cs[6]=array(2,1,1,'5a625YW35a6255S15pyN5Yqh');
$cfg_Cs[7]=array(2,1,1,'56m66LCD56e75py65pyN5Yqh');
$cfg_Cs[8]=array(2,1,1,'5L+d5rSB5a625pS/5pyN5Yqh');
$cfg_Cs[9]=array(0,1,1,'UHJvZHVjdHM=');
$cfg_Cs[10]=array(0,1,1,'TmV3cw==');
$cfg_Cs[15]=array(0,1,1,'VGVjaG5vbG9neQ==');
$cfg_Cs[16]=array(0,1,1,'U2VydmljZXM=');
$cfg_Cs[13]=array(0,1,1,'TWVzc2FnZQ==');
$cfg_Cs[14]=array(0,1,1,'Q29udGFjdA==');
?>