<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n            <li class=\"smallnav\"><a href=\"/en[field:typeurl/]#content\" title=\"[field:typename/]\"><span>&gt;</span>[field:typename/]</a></li>\r\n            ",1707,2055);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="2";
$z[5][4]['currentstyle']="<li class='hover'><a href='/en~typelink~#content' ~rel~><span>~typename~</span></a></li>";
$z[6]=Array("field","",2664,2693);
$z[6][4]['name']="typename";
$z[7]=Array("type","<a href=\"/en[field:typelink /]\">[field:typename /]</a>",2743,2820);
$z[8]=Array("field","",2903,2922);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",2969,2986);
$z[10]=Array("field","",3001,3057);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",3186,3204);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",3524,3549);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",3587,3613);
$z[13][4]['get']="next";
$z[14]=Array("include","",3754,3791);
$z[14][4]['filename']="footer.htm";

?>