<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",819,854);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n            <li class=\"smallnav\"><a href=\"[field:typeurl/]#content\" title=\"[field:typename/]\"><span>&gt;</span>[field:typename/]</a></li>\r\n            ",1676,2018);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="2";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~#content' ~rel~><span>~typename~</span></a></li>";
$z[6]=Array("field","",2591,2620);
$z[6][4]['name']="typename";
$z[7]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",2669,2743);
$z[8]=Array("field","",2826,2845);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",2898,2915);
$z[10]=Array("field","",2931,2987);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",3116,3134);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",3454,3479);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",3517,3543);
$z[13][4]['get']="next";
$z[14]=Array("include","",3684,3721);
$z[14][4]['filename']="footer.htm";

?>