<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",834,869);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n            <li class=\"smallnav\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><span>&gt;</span>[field:typename/]</a></li>\r\n            ",1664,1990);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="2";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[6]=Array("field","",2563,2592);
$z[6][4]['name']="typename";
$z[7]=Array("field","",2641,2670);
$z[7][4]['name']="position";
$z[8]=Array("field","",2753,2772);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",2825,2842);
$z[10]=Array("field","",2858,2914);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",3043,3061);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",3374,3399);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",3437,3463);
$z[13][4]['get']="next";
$z[14]=Array("include","",3589,3626);
$z[14][4]['filename']="footer.htm";

?>