<?php
$z[0]=Array("global","",110,135);
$z[0][4]['name']="autoindex";
$z[1]=Array("global","",158,183);
$z[1][4]['name']="autoindex";
$z[2]=Array("picname","",189,205);
$z[3]=Array("global","",216,241);
$z[3][4]['name']="autoindex";
$z[4]=Array("global","",264,289);
$z[4][4]['name']="autoindex";
$z[5]=Array("arcurl","",295,310);
$z[6]=Array("global","",323,348);
$z[6][4]['name']="autoindex";
$z[7]=Array("title","",350,364);

?>