<?php
$z[0]=Array("global","",37,63);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",103,129);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("globel","",275,302);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",690,716);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]#content\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",747,1012);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>