<?php
$z[0]=Array("global","",39,65);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",108,134);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",637,663);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n      <li><a href=\"/en[field:typeurl/]#content\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",686,965);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li><a href='/en~typelink~#content' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>