<?php
$z[0]=Array("global","",37,63);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",103,129);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",388,414);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",445,702);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li><a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";

?>