<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",819,854);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",882,917);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n            <li class=\"smallnav\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><span>&gt;</span>[field:typename/]</a></li>\r\n            ",1711,2037);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['typeid']="2";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[7]=Array("field","",2610,2639);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2688,2717);
$z[8][4]['name']="position";
$z[9]=Array("field","",2800,2819);
$z[9][4]['name']="title";
$z[10]=Array("adminname","",2872,2889);
$z[11]=Array("field","",2905,2961);
$z[11][4]['name']="pubdate";
$z[11][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[12]=Array("field","",3090,3108);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",3421,3446);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",3484,3510);
$z[14][4]['get']="next";
$z[15]=Array("include","",3651,3688);
$z[15][4]['filename']="footer.htm";

?>