<?php
$z[0]=Array("flink","  [field:link /]  ",112,190);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",306,332);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n	<a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n		  ",406,661);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<a href='~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";
$z[3]=Array("global","",1017,1043);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",1219,1243);
$z[4][4]['name']="cfg_beian";

?>