<?php
$z[0]=Array("global","",526,552);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n	<a href=\"/en[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n		  ",596,846);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<a href='/en~typelink~' ~rel~ class='hover'><span>~typename~</span></a></li>";
$z[2]=Array("global","",1000,1026);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",1110,1134);
$z[3][4]['name']="cfg_beian";

?>