<?php
$z[0]=Array("global","",266,292);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",333,362);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",402,460);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",836,871);
$z[3][4]['filename']="head.htm";
$z[4]=Array("channel","\r\n            <li class=\"smallnav\"><a href=\"/en[field:typeurl/]#content\" title=\"[field:typename/]\"><span>&gt;</span>[field:typename/]</a></li>\r\n            ",1716,2064);
$z[4][4]['type']="son";
$z[4][4]['row']="10";
$z[4][4]['typeid']="2";
$z[4][4]['currentstyle']="<li class='hover'><a href='/en~typelink~#content' ~rel~><span>~typename~</span></a></li>";
$z[5]=Array("global","",2738,2793);
$z[5][4]['name']="keyword";
$z[5][4]['function']="RemoveXSS(@me)";
$z[6]=Array("list","\r\n          <li><a href=\"/en[field:arcurl/]#content\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n          ",2918,3125);
$z[6][4]['perpage']="20";
$z[7]=Array("pagelist","",3211,3264);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[8]=Array("include","",3382,3419);
$z[8][4]['filename']="footer.htm";

?>